services:
  - type: web
    name: revdlo-assembly
    runtime: python
    rootDir: assembly-service
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 300 --workers 1
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: COUNCIL_SECRET
        sync: false
    plan: free
